name: ci-golang
on: [push]

jobs:
  check-application: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm run test
      - run: npm run start